project:
  type: website

website:
  title: "Modern Banking and Financial Technology"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: syllabus.qmd
        text: Syllabus
      - href: schedule.qmd
        text: Schedule
      - text: Lectures
        menu:
          - href: 'lectures/lecture_01/lecture_01.qmd'
            text: Lecture 01 - Modern Banking pt. 1 
          - href: 'lectures/lecture_02/lecture_02.qmd'
            text: Lecture 02 - Modern Banking pt. 2 
          - href: 'lectures/lecture_03/lecture_03.qmd'
            text: Lecture 03 - Modern Banking pt. 3
          - href: 'lectures/lecture_04/lecture_04.qmd'
            text: Lecture 04 - Modern Banking pt. 4 
          - href: 'lectures/lecture_05/lecture_05.qmd'
            text: Lecture 05 - Fintech | Plaforms pt. 1
          - href: 'lectures/lecture_06/lecture_06.qmd'
            text: Lecture 06 -  Modern Banking pt. 5 
          - href: 'lectures/lecture_07/lecture_07.qmd'
            text: Lecture 07 - Platforms pt. 2
          - href: 'lectures/lecture_08/lecture_08.qmd'
            text: Lecture 08 - Machine Learning pt. 1
          - href: ''
            text: Lecture 09 - Machine Learning pt. 2
          - href: ''
            text: Lecture 10 - Crypto pt. 1
          - href: ''
            text: Lecture 11 - Crypto pt. 2
      - href: 'https://app.alldayta.com/katholieke-universiteit-leuven/mbft'
        text: All Day TA
      - href: assignment.qmd
        text: Assignment (**NEW**)

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-location: left
    # number-sections: true

bibliography: refs.bib



